# ETL Project

Weston Eckloff

AIRPORT DATASET

In [1]:
import os
import csv
import numpy as np
import pandas as pd
from sqlalchemy import create_engine

In [2]:
airports_csv = os.path.join("Data", "airports.csv")
airports_df = pd.read_csv(airports_csv)
airports_df.head()

,IATA,AIRPORT,CITY,STATE,COUNTRY,LATITUDE,LONGITUDE
0,ABQ,Albuquerque International,Albuquerque,NM,USA,35.040222,-106.609194
1,ANC,Ted Stevens Anchorage International,Anchorage,AK,USA,61.174320,-149.996186
2,ATL,William B Hartsfield-Atlanta Intl,Atlanta,GA,USA,33.640444,-84.426944
3,AUS,Austin-Bergstrom International,Austin,TX,USA,30.194533,-97.669872
4,BDL,Bradley International,Windsor Locks,CT,USA,41.938874,-72.683228

In [3]:
del airports_df['COUNTRY']
del airports_df['LATITUDE']
del airports_df['LONGITUDE']
airports_df.head()

  IATA                              AIRPORT           CITY STATE
0  ABQ            Albuquerque International    Albuquerque    NM
1  ANC  Ted Stevens Anchorage International      Anchorage    AK
2  ATL    William B Hartsfield-Atlanta Intl        Atlanta    GA
3  AUS       Austin-Bergstrom International         Austin    TX
4  BDL                Bradley International  Windsor Locks    CT

In [4]:
airports_unique = airports_df['AIRPORT'].unique()
print(len(airports_unique))
print(airports_unique)

341
['Albuquerque International' 'Ted Stevens Anchorage International'
 'William B Hartsfield-Atlanta Intl' 'Austin-Bergstrom International'
 'Bradley International' 'Birmingham International'
 'Nashville International' 'Gen Edw L Logan Intl' 'Buffalo Niagara Intl'
 'Burbank-Glendale-Pasadena' 'Baltimore-Washington International'
 'Charleston AFB International' 'Cleveland-Hopkins Intl'
 'Charlotte Douglas International' 'Port Columbus Intl'
 'Cincinnati Northern Kentucky Intl' 'Dallas Love '
 'Ronald Reagan Washington National' 'Denver Intl'
 'Dallas-Fort Worth International' 'Detroit Metropolitan-Wayne County'
 'El Paso International' 'Newark Intl' "Fort Lauderdale-Hollywood Int'l"
 'Honolulu International' 'William P X' 'Washington Dulles International'
 'George Bush Intercontinental' 'Indianapolis International'
 'Jacksonville International' 'John F Kennedy Intl'
 'McCarran International' 'Los Angeles International' 'LaGuardia' 'Adams '
 'Kansas City International' 'Orlando International' 'Chicago Midway'
 'Memphis International' 'Miami International'
 'General Mitchell International' 'Minneapolis-St Paul Intl'
 'New Orleans International ' 'Metropolitan Oakland International'
 'Kahului' 'Will Rogers World' 'Eppley Airfield' 'Ontario International'
 "Chicago O'Hare International" 'Norfolk International'
 'Palm Beach International' 'Portland Intl' 'Philadelphia Intl'
 'Phoenix Sky Harbor International' 'Pittsburgh International'
 'Theodore F Green State' 'Raleigh-Durham International'
 'Richmond International' 'Reno Tahoe International'
 'Southwest Florida International' 'San Diego International-Lindbergh '
 'San Antonio International' 'Louisville International-Standiford '
 'Seattle-Tacoma Intl' 'San Francisco International'
 'San Jose International' 'Luis Munoz Marin International'
 'Salt Lake City Intl' 'Sacramento International' 'John Wayne  Orange Co'
 'Lambert-St Louis International' 'Tampa International '
 'Tulsa International' 'Tucson International'
 'Lehigh Valley International' 'Abilene Regional' 'Aberdeen Regional'
 'Southwest Georgia Regional' 'Nantucket Memorial' 'Waco Regional'
 'Arcata' 'Atlantic City International' 'Adak' 'Kodiak '
 'Alexandria International' 'Bush ' 'King Salmon' 'Albany Cty'
 'Waterloo Municipal' 'Amarillo International' 'Alpena County Regional '
 'Watertown Intl' 'Aspen-Pitkin Co Sardy ' 'Outagamie County Regional'
 'Asheville Regional' 'Wilkes-Barre Scranton Intl' 'Kalamazoo County'
 'Bethel' 'Meadows ' 'Binghamton Regional' 'Bangor International'
 'Billings Logan Intl' 'Bismarck Municipal' 'Bemidji-Beltrami County'
 'Bellingham Intl' 'Central Illinois Regional' 'Boise Air Terminal'
 'Southeast Texas Regional' 'Glynco Jetport' 'Rafael Hernandez'
 'Brainerd-Crow Wing County Regional'
 'Brownsville S.Padre Island International'
 'Wiley Post Will Rogers Memorial' 'Bert Mooney'
 'Baton Rouge Metropolitan' 'Burlington International' 'Gallatin '
 'Columbia Metropolitan' 'Akron-Canton Regional' 'Cedar City Muni'
 'Merle K (Mudhole) Smith' 'Jack McNamara ' 'Lovell '
 'Charlottesville-Albermarle' 'Chico Municipal' 'Eastern Iowa '
 'Chippewa County International' 'MC Clellan-Palomar Airport'
 'Easterwood ' 'University of Illinois-Willard' 'Houghton County Memorial'
 'Canyonlands ' 'Yellowstone Regional' 'City of Colorado Springs Muni'
 'Columbia Regional' 'Natrona County Intl' 'Corpus Christi International'
 'Yeager' 'Columbus Metropolitan' 'Central Wisconsin' 'Cheyenne'
 'Daytona Beach International' 'James M Cox Dayton Intl'
 'Dubuque Municipal' 'Dothan ' 'Dickinson Municipal' 'Dillingham'
 'Duluth International' 'Durango-La Plata County' 'Del Rio International'
 'Des Moines International' 'Devils Lake Municipal-Knoke '
 'Chippewa Valley Regional' 'Eagle County Regional' 'Elko Regional'
 'Elmira Corning Regional' 'Erie Intl' 'Delta County' 'Mahlon Sweet '
 'Evansville Regional' 'Craven County Regional' 'Key West International'
 'Fairbanks International' 'Hector International'
 'Fresno Yosemite International' 'Fayetteville Municipal'
 'Glacier Park Intl' 'Flagstaff Pulliam' 'Florence Regional' 'Bishop'
 'Forbes ' 'Joe Foss ' 'Fort Smith Regional' 'Fort Wayne International'
 'Gillette-Campbell County' 'Garden City Regional' 'Spokane Intl'
 'Grand Forks International' 'Gregg County' 'Walker '
 'Gainesville Regional' 'Gulfport-Biloxi Regional'
 'Austin Straubel International' 'Central Nebraska Regional '
 'Robert Gray AAF' 'Kent County International'
 'Piedmont Triad International' 'Greenville-Spartanburg' 'Gustavus'
 'Great Falls Intl' 'Golden Triangle Regional' 'Gunnison County'
 'Guam International' 'Yampa Valley' 'Chisholm-Hibbing' 'Helena Regional'
 'Lea County Regional' 'Westchester Cty' 'Valley International'
 'Huntsville International ' 'Tri-State Walker-Long '
 'Barnstable Mun Boardman Polando ' 'Hays Municipal'
 'Wichita Mid-Continent' 'Idaho Falls Regional' 'New Castle County '
 'Wilmington International' 'Ford' 'Falls International' 'Imperial County'
 'Sloulin Field International' 'Long Island - MacArthur' 'Tompkins Cty '
 'Hilo International' 'Inyokern' 'Jackson Hole' 'Jackson International'
 'Joplin Regional' 'Jamestown Municipal' 'Juneau International'
 'Kona International At Keahole' 'Ketchikan International' 'Capital City'
 'Laramie Regional' 'Lawton-Ft Sill Regional' 'Lubbock International'
 'Lake Charles Regional' 'Blue Grass ' 'Lafayette Regional'
 'Long Beach (Daugherty )' 'Lihue' 'Klamath Falls International'
 'Lincoln Municipal' 'Laredo International' 'La Crosse Municipal'
 'Greenbrier Valley' 'Lewiston-Nez Perce County'
 'Lynchburg Municipal-Preston Glenn ' 'Midland International'
 'Mbs International' 'Middle Georgia Regional' 'Harrisburg Intl' 'Key '
 'McAllen Miller International' 'Rogue Valley International'
 'Montgomery Regional Apt' 'Manhattan Regional' 'Manchester'
 'Muskegon County' 'Melbourne International ' 'Quad City'
 'Monroe Regional' 'Mammoth Yosemite' 'Mobile Regional'
 'Modesto City-County-Harry Sham ' 'Minot International'
 'Marquette County Airport' 'Monterey Peninsula' 'Dane County Regional'
 'Missoula International' 'Montrose Regional' 'Marthas Vineyard'
 'Grant County' 'Myrtle Beach International' 'Albert J Ellis' 'Nome'
 'Worcester Regional' 'North Bend Muni' 'Ralph Wien Memorial' 'Oxnard'
 'Barkley Regional' 'Panama City-Bay County International'
 'Newport News Williamsburg International' 'Greater Peoria Regional'
 'Hattiesburg-Laurel Regional' 'St. Petersburg-Clearwater International'
 'Pocatello Regional' 'Pierre Regional'
 'Pellston Regional  of Emmet County' 'Pensacola Regional'
 'Pago Pago International' 'Tri-Cities' 'Mercedita'
 'James C. Johnson Petersburg' 'Palm Springs International'
 'Pueblo Memorial' 'Portland International Jetport' 'Rapid City Regional'
 'Redding Municipal' 'Roberts ' 'Greater Rockford'
 'Rhinelander-Oneida County' 'Rock Springs-Sweetwater County'
 'Roanoke Regional  Woodrum ' "Greater Rochester Int'l"
 'Roswell Industrial Air Center' 'Rochester International'
 'Santa Fe Municipal' 'Savannah International' 'Santa Barbara Municipal'
 'South Bend Regional' 'San Luis Obispo Co-McChesney ' 'Deadhorse'
 'University Park' 'Springfield-Branson Regional' 'St George Muni'
 'Shenandoah Valley Regional' 'Shreveport Regional' 'Sitka'
 'San Angelo Regional  Mathis ' 'Santa Maria Pub Capt G Allan Hancock '
 'Capital' 'Tinian International Airport'
 'Sheppard AFB Wichita Falls Municipal' 'Sarasota Bradenton International'
 'St Cloud Regional' 'Cyril E. King' 'Henry E. Rohlsen '
 'Friedman Memorial' 'Sioux Gateway ' 'Stewart' 'Syracuse-Hancock Intl'
 'Telluride Regional' 'Tallahassee Regional' 'Toledo Express'
 'Tri-Cities Regional' 'Trenton-Mercer County ' 'Tupelo Municipal '
 'Cherry Capital' 'Joslin Field - Magic Valley' 'Texarkana Regional-Webb '
 'Tyler Pounds ' 'McGhee-Tyson' 'Vernal' 'Valdosta Regional'
 'Eglin Air Force Base' 'Wrangell' 'Yellowstone'
 'Northwest Arkansas Regional' 'Yakutat' 'Yuma MCAS-Yuma International']

AIRLINE DELAY DATASET

In [8]:
delay_csv = os.path.join("Data", "airline_delay_causes.csv")
delay_df = pd.read_csv(delay_csv)
del delay_df['Unnamed: 21']
delay_df.head()

,year,month,carrier,carrier_name,airport,airport_name,arr_flights,arr_del15,carrier_ct,weather_ct,...,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
0,2004,1,DL,Delta Air Lines Inc.,PBI,"West Palm Beach/Palm Beach, FL: Palm Beach Int...",650.0,126.0,21.06,6.44,...,1.0,45.92,4.0,0.0,5425.0,881.0,397.0,2016.0,15.0,2116.0
1,2004,1,DL,Delta Air Lines Inc.,PDX,"Portland, OR: Portland International",314.0,61.0,14.09,2.61,...,0.0,10.05,30.0,3.0,2801.0,478.0,239.0,1365.0,0.0,719.0
2,2004,1,DL,Delta Air Lines Inc.,PHL,"Philadelphia, PA: Philadelphia International",513.0,97.0,27.60,0.42,...,0.0,17.12,15.0,0.0,4261.0,1150.0,16.0,2286.0,0.0,809.0
3,2004,1,DL,Delta Air Lines Inc.,PHX,"Phoenix, AZ: Phoenix Sky Harbor International",334.0,78.0,20.14,2.02,...,0.0,16.45,3.0,1.0,3400.0,1159.0,166.0,1295.0,0.0,780.0
4,2004,1,DL,Delta Air Lines Inc.,PIT,"Pittsburgh, PA: Pittsburgh International",217.0,47.0,8.08,0.44,...,0.0,16.59,4.0,1.0,1737.0,350.0,28.0,522.0,0.0,837.0

In [28]:
delay_filtered = delay_df[(delay_df.year == 2019)]
delay_filtered['City'], delay_filtered['State'] = delay_filtered['airport_name'].str.rsplit(', ').str

delayed_filtered.head()

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Columnar iteration over characters will be deprecated in future releases.

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

NameError: name 'delayed_filtered' is not defined

ENPLANEMENT DATASET

In [20]:
enplanement_csv = os.path.join("Data", "2019-enplanements.csv")
enplanement_df = pd.read_csv(enplanement_csv)
enplanement_df.head()

,Rank,RO,ST,Locid,City,Airport Name,S/L,Hub,CY 19 Enplanements,CY 18 Enplanements,% Change
0,58.0,AL,AK,ANC,Anchorage,Ted Stevens Anchorage International,P,M,"2,713,843","2,642,607",2.70%
1,124.0,AL,AK,FAI,Fairbanks,Fairbanks International,P,S,"562,420","549,289",2.39%
2,146.0,AL,AK,JNU,Juneau,Juneau International,P,N,"401,917","440,277",-8.71%
3,204.0,AL,AK,BET,Bethel,Bethel,P,N,"160,874","160,110",0.48%
4,215.0,AL,AK,KTN,Ketchikan,Ketchikan International,P,N,"137,090","135,389",1.26%

#